README.md, README.pt-br.md
Adding English Documentation and link to other documentation languages.
=> Add mutiple readmes

README.md
I've replaced Portuguese comments with English. 👍
=> Replace Portuguese comments

lib/src/widgets/consumer_widget.dart, lib/src/widgets/modular_app.dart
=> Clear injected objects before super.dispose()

README.pt-br.md
Não sou nenhum especialista em linguagens, mas creio que assim ficaria melhor
=> Apenas algumas sugestões parar melhorar a tradução

README.md, README.pt-br.md, test/modular_app_test.dart
=> Melhorias no Readme

lib/src/test/utils_test.dart, test/modular_test_test.dart
Estava testando um aplicativo e precisei testar se a navegação estava funcionando ao clicar em um botão, com essas alterações consegui chegar ao resultado que esperava.
=> initModule com Modular.bindModule ou Modular.init

lib/src/modular_base.dart
kReleaseMode contains if flutter is running in release mode, I used this variable to initialize Modular.debug mode.
=> Automatic init debugMode variable

lib/src/modular_base.dart, test/app/modules/home/home_module.dart, test/modular_test_test.dart
Teste do Modular.args usando o Modular.arguments na hora do teste para passar os parâmetros necessários
=> Test Modular.args and new feature Modular.arguments

README.md, README.pt-br.md, lib/src/routers/router.dart
- Add hability to group routes by commom properties like `guards`, `transition` and `customTransition`
- Some fixes on **README.md** and **README.pt-br.md** files and fix missing translations.
=> Add 'group' static method to Router

example/test/app/modules/tabs/modules/tab1/pages/page1/page1_bloc_test.dart, example/test/app/modules/tabs/modules/tab1/pages/page1/page1_page_test.dart, example/test/app/modules/tabs/modules/tab1/pages/page2/page2_bloc_test.dart, example/test/app/modules/tabs/modules/tab1/pages/page2/page2_page_test.dart, example/test/app/modules/tabs/modules/tab1/tab1_bloc_test.dart, example/test/app/modules/tabs/modules/tab1/tab1_page_test.dart, example/test/app/modules/tabs/modules/tab2/tab2_bloc_test.dart, example/test/app/modules/tabs/modules/tab2/tab2_page_test.dart, example/test/app/modules/tabs/tabs_bloc_test.dart, example/test/app/modules/tabs/tabs_page_test.dart, test/modular_app_test.dart, test/modular_stack_overflow_test.dart
=> remove warnings

.github/workflows/dart.yml, lib/src/interfaces/child_module.dart, lib/src/modular_base.dart, test/app/modules/home/home_module.dart, test/app/modules/home/home_widget.dart, test/app/shared/app_info.state.dart, test/modular_inject_test.dart
I've added unit test to ensure singleton injection work.
I also did a performance enhancement to avoid looping over the list again **_getInjectableObject**
Also fixed build on github actions =D 
Fixes #85
=> Added unit test to ensure singleton injection works

lib/src/inject/bind.dart
The logic expression in the assertion is equivalent to an OR, so i have changed to improve readability.
=> Improving readability of the assertion at bind.dart

example/pubspec.lock, lib/src/modular_base.dart, pubspec.lock
Add parameter defaultValue para o Get, usefull when work with separeted modules
=> Add parameter defaultValue para o Get

README.md, README.pt-br.md
As requested by @irvine5k, I reviewed the English documentation (README) and provided a improved text wherever I could.
=> English documentation review

lib/src/inject/inject.dart, lib/src/interfaces/child_module.dart, lib/src/modular_base.dart, lib/src/navigator/modular_navigator.dart, lib/src/navigator/modular_navigator_interface.dart
Colocando DartDoc nas classes de navegação
=> documentação de modular_navigator_interface

example/pubspec.lock, lib/src/inject/inject.dart, pubspec.lock, test/app/modules/home/home_module.dart
=> Add default value

flutter_modular/README.md
Fixed README.md index to open hyperlinks correctly
=> fix README.md index

flutter_modular/README.md
Improving documentation about dynamic routes, like this question on the [issue#297](https://github.com/Flutterando/modular/issues/297). Simple changing, showing how we can use the same dynamic route on two different pages.
=> Improving documentation on dynamic routes.

flutter_modular/lib/src/presenters/modular_route_impl.dart, flutter_modular/lib/src/presenters/navigation/modular_route_information_parser.dart
=> Fix empty params & queryParams updates issue

flutter_modular/lib/src/presenters/navigation/modular_router_delegate.dart
=> Fix a typo.

flutter_modular/example/lib/app/search/domain/usecases/search_by_text.dart, flutter_modular/example/lib/app/search/external/github/github_search_datasource.dart, flutter_modular/example/lib/app/search/infra/repositories/search_repository_impl.dart, flutter_modular/example/pubspec.yaml, flutter_modular/example/test/app/app_module_test.dart, flutter_modular/example/test/app/search/domain/usecases/search_by_text_test.dart, flutter_modular/example/test/app/search/external/github/github_search_datasource_test.dart, flutter_modular/example/test/app/search/infra/repositories/search_repository_impl_test.dart
- Updates code to match new http's API
- Updates tests to use new mocktail's API
- Fixes error "EmptyList" not being returned
- Fixes broken tests
=> Updates the example

flutter_modular/example/pubspec.yaml
=> Fix dependency in example

flutter_modular/example/lib/app/search/presenter/pages/search_page.dart
The example should be in english. So this PR does just that: translates some literals.
OBS.: it's only failing because of problems which already existed on master. #336 and #337 should fix it.
=> Updates example language

flutter_modular/example/linux/.gitignore, flutter_modular/example/linux/CMakeLists.txt, flutter_modular/example/linux/flutter/CMakeLists.txt, flutter_modular/example/linux/flutter/generated_plugin_registrant.cc, flutter_modular/example/linux/flutter/generated_plugin_registrant.h, flutter_modular/example/linux/flutter/generated_plugins.cmake, flutter_modular/example/linux/main.cc, flutter_modular/example/linux/my_application.cc, flutter_modular/example/linux/my_application.h
Just that.
OBS.: it's only failing because of problems which already existed on master. #336 and #337 should fix it.
=> Adds linux support to example

flutter_modular/example/linux/flutter/generated_plugin_registrant.cc, flutter_modular/example/linux/flutter/generated_plugin_registrant.h, flutter_modular/example/macos/Flutter/GeneratedPluginRegistrant.swift, flutter_modular/example/windows/flutter/generated_plugin_registrant.cc, flutter_modular/example/windows/flutter/generated_plugin_registrant.h, flutter_modular/lib/src/presenters/widgets/widget_module.dart
fixes missing Module interfaces: `get imports` and `getInjectedBind()…
=> WidgetModule fixes

flutter_modular/README.md, flutter_modular/analysis_options.yaml, flutter_modular/example/lib/app/search/presenter/pages/search_page.dart, flutter_modular/lib/src/presenters/navigation/modular_router_delegate.dart, flutter_modular/lib/src/presenters/navigation/router_outlet_delegate.dart, flutter_modular/pubspec.yaml
This PR fixes the README and the analyzer warnings
=> Fix README and analyzer warnings

flutter_modular/README.md
Only few change on the documentation of flutter_modular on the part of Routes.
=> Small change on the docs (Routes)

flutter_modular/README.md
* Documentation menu organized.
* Explained about ModularState.
* When and how using about navigate/pushNamed.
* Explained about Stack.
=> Refactoring README.md and clean some parts

flutter_modular/README.md
Hi, this PR aims to solve #410. I've added an example of how to use isModuleReady alongside RouteGuard which is how I'm using it in my projects.
=> Added isModuleReady to README.md

flutter_modular/lib/src/core/interfaces/modular_route.dart
=> fix typo in modular_route.dart

flutter_modular/lib/src/core/interfaces/modular_route.dart, flutter_modular/lib/src/core/interfaces/route_guard.dart, flutter_modular/lib/src/presenters/navigation/modular_route_information_parser.dart, flutter_modular/test/src/core/interfaces/route_guard_test.dart, flutter_modular/test/src/presenters/navigation/modular_route_information_parse_test.dart
ModularRoute.guardedRoute moved to RouteGuard
=> move guardedRoute ModularRoute->RouteGuard

flutter_modular/example/lib/app/search/presenter/pages/guardt.dart, flutter_modular/example/linux/flutter/generated_plugin_registrant.cc, flutter_modular/example/linux/flutter/generated_plugin_registrant.h
fix example RouteGuard, to atual modular version.
=> fix: create constructor with right params

flutter_modular/lib/src/presenters/navigation/modular_router_delegate.dart
This fixes the #454 issue of navigation with backbutton on web.
=> fix: remove fromModular on setNewRoutePath replace pages check

flutter_modular/example/lib/app/app_module.dart, flutter_modular/example/lib/app/search/presenter/pages/guardt.dart
Solves this:
```
The superclass 'RouteGuard' doesn't have a zero argument constructor.
Try declaring a zero argument constructor in 'RouteGuard', or declaring a constructor in GuardT that explicitly invokes a constructor in 'RouteGuard'.
```
=> Fixes example code not compiling

flutter_modular/example/test/app/app_module_test.dart, flutter_modular/example/test/app/search/external/github/github_search_datasource_test.dart
Makes its tests pass again :tada:
=> Fixes example's tests

flutter_modular/lib/src/presenters/modular_route_impl.dart, flutter_modular/test/src/core/inject/bind_test.dart, flutter_modular/test/src/core/models/bind_test.dart, flutter_modular/test/src/core/models/modular_arguments_test.dart, flutter_modular/test/src/core/models/modular_router_test.dart, flutter_modular/test/src/presenters/navigation/modular_async_binds_test.dart
- Translates assertion from Portuguese to English
- Deletes tests which aren't asserting anything
- Adds tests
- Refactors some tests
- Improves naming
- Formats code
- Creates groups to increase readability
=> Refactors the tests and adds some

modular_codegen/lib/src/injection_generator.dart
=> fix: injection generator

doc/docs/flutter_modular/start.md
* Start part is documentation now is in English.
=> Finished start doc

flutter_modular/.gitignore, flutter_modular/CHANGELOG.md, flutter_modular/lib/src/presenter/navigation/modular_router_delegate.dart, flutter_modular/pubspec.yaml, modular_core/CHANGELOG.md, modular_core/lib/src/route/tracker.dart, modular_core/pubspec.yaml, modular_core/test/src/route/tracker_test.dart, modular_test/lib/modular_test.dart, modular_test/test/modular_test_test.dart
* Fixed pushNamed.
* Fixed bug that allowed access to parameters and arguments in other modules.
* Fixed transitions bug.
=> version 4.0.1

doc/docs/flutter_modular/start.md
Adjusted grammar and some phrasing to reflect more common English word choices.  For example, switching "paternity links" (which is almost always a medical term) to "links to the parent" (common programming phrasing).
=> English translation and grammar improvements.

doc/docs/flutter_modular/module.md, doc/docs/flutter_modular/navegation.md, doc/docs/flutter_modular/test.md, flutter_modular/lib/src/presenter/models/modular_navigator.dart, flutter_modular/lib/src/presenter/navigation/modular_router_delegate.dart, flutter_modular/test/src/presenter/navigation/modular_router_delegate_test.dart
A propriedade `Modular.to.navigateHistory `retorna uma lista do historico das rotas
=> Deixando publico para leitura historico da navegação de rotas

flutter_modular/lib/src/presenter/models/route.dart, flutter_modular/lib/src/presenter/navigation/modular_page.dart
This solution allows the custom route to carry more complex transitions, including but not limited to modal style transitions.
=> CustomTransition Expansion

doc/docs/flutter_modular/navegation.md
i wasted 2 hours finding this out xD
=> looks like a spelling mistake

modular_codegen/README.md
I want to be reviewed my poor English.
=> more understandable for  beginners

.github/pull_request_template.md, .github/workflows/title-validation.yml, CONTRIBUTING.md
=> ci: add PR starts with a [Conventional Commit] prefix validation

plugins/modular_bloc_bind/CHANGELOG.md, plugins/modular_bloc_bind/example/pubspec.yaml, plugins/modular_bloc_bind/lib/src/modular_bloc_bind_base.dart, plugins/modular_bloc_bind/pubspec.yaml
=> feat: Cubit support

flutter_modular/CHANGELOG.md, flutter_modular/lib/flutter_modular.dart, flutter_modular/lib/src/presenter/navigation/modular_route_information_parser.dart, flutter_modular/lib/src/presenter/widgets/widget_module.dart, flutter_modular/pubspec.yaml, flutter_modular/test/src/infra/services/bind_service_impl_test.dart
=> fix: Parse params in RouteOutlet

modular_codegen/pubspec.yaml
Changes max version of build in modular_codegen
Fixes #741
=> fix: Change max build version on modular_codegen

doc/docs/flutter_modular/dependency-injection.md
No exemplo utilizado faltou declarar o nome da variável XPTOEmail
=> fix(doc): nome da variável

doc/docs/flutter_modular/navegation.md
=> fix: typo in navegation.md

.github/workflows/dart.yml, README.md
=> fix: UpdateFlutter version in dart.yml

shelf_modular/CHANGELOG.md
=> fix: Update CHANGELOG.md

shelf_modular/CHANGELOG.md, shelf_modular/example/lib/src/app_module.dart, shelf_modular/example/lib/src/auth/auth_module.dart, shelf_modular/example/lib/src/auth/presenter/guards/auth_guard.dart, shelf_modular/lib/shelf_modular.dart, shelf_modular/lib/src/infra/services/route_service_impl.dart, shelf_modular/lib/src/presenter/errors/errors.dart, shelf_modular/lib/src/presenter/middlewares/middlewares.dart, shelf_modular/lib/src/presenter/models/bind.dart, shelf_modular/lib/src/presenter/models/route.dart, shelf_modular/lib/src/presenter/modular_base.dart, shelf_modular/lib/src/shelf_modular_module.dart, shelf_modular/pubspec.yaml, shelf_modular/test/src/infra/services/route_service_impl_test.dart, shelf_modular/test/src/presenter/modular_base_test.dart
=> fix: binds and format

shelf_modular/CHANGELOG.md, shelf_modular/lib/src/presenter/resources/websocket_resource.dart, shelf_modular/pubspec.yaml
=> feat: add broadcast

.github/workflows/dart.yml
=> feat: Update dart.yml

README.md
Nao esta pronto, subir para salvar o que fiz ate agora
=> docs: Padronização do readme realizada

doc/docs/shelf_modular/routes.md
=> body is positional parameter

modular_codegen/pubspec.yaml
This pr change analyzer version to 3.4.0  for resolve conflicts with others packages.
- [x ] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [X ] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ X] I have updated/added tests for ALL new/updated/fixed functionality.
- [ X] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ X] I have updated/added relevant examples in `examples`.
- [ X] No, this is *not* a breaking change.
=> Chore: Change analyzer version

.github/workflows/dart.yml
=> chore: Update dart.yml

doc/docs/flutter_modular/navegation.md
Small improvements on the wording, nothing too important but wanted to help correct this. Thanks for this great package!
=> docs: Update navegation.md

doc/docs/flutter_modular/start.md, flutter_modular/CHANGELOG.md, flutter_modular/lib/flutter_modular.dart, flutter_modular/pubspec.yaml, modular_core/pubspec.yaml, shelf_modular/example/pubspec.lock
=> docs: Modular 6.0.1

flutter_modular/CHANGELOG.md, flutter_modular/lib/src/flutter_modular_module.dart, flutter_modular/lib/src/infra/services/url_service/html_url_service.dart, flutter_modular/lib/src/infra/services/url_service/io_url_service.dart, flutter_modular/lib/src/infra/services/url_service/url_service.dart, flutter_modular/lib/src/presenter/modular_base.dart, flutter_modular/lib/src/presenter/navigation/modular_route_information_parser.dart, flutter_modular/lib/src/presenter/widgets/modular_app.dart, flutter_modular/pubspec.yaml, flutter_modular/test/src/infra/services/url_service/html_url_service_test.dart, flutter_modular/test/src/presenter/modular_base_test.dart, flutter_modular/test/src/presenter/navigation/modular_route_information_parser_test.dart, modular_core/pubspec.yaml
=> fix: Modular 6.0.2

flutter_modular/CHANGELOG.md, flutter_modular/lib/src/domain/services/bind_service.dart, flutter_modular/lib/src/domain/usecases/replace_instance.dart, flutter_modular/lib/src/infra/services/bind_service_impl.dart, flutter_modular/lib/src/presenter/modular_base.dart, flutter_modular/lib/src/presenter/navigation/modular_router_delegate.dart, flutter_modular/pubspec.yaml, flutter_modular/test/src/infra/services/bind_service_impl_test.dart, flutter_modular/test/src/presenter/modular_base_test.dart, modular_core/pubspec.yaml
=> fix: pushNamedAndRemoveUntil

flutter_modular/CHANGELOG.md, flutter_modular/pubspec.yaml, modular_core/CHANGELOG.md, modular_core/lib/src/tracker.dart, modular_core/pubspec.yaml
=> Fix: phantom dependencies.

flutter_modular/CHANGELOG.md, flutter_modular/example/windows/flutter/CMakeLists.txt, flutter_modular/example/windows/runner/flutter_window.cpp, flutter_modular/pubspec.yaml
=> change version

flutter_modular/lib/src/presenter/navigation/modular_route_information_parser.dart
=> feat: add logging for initial route and improve path handling in ModularRouteInformationParser #987 #930 #900
